# Makefile.in generated by automake 1.11.1 from Makefile.am.
# cgi/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/bas
pkgincludedir = $(includedir)/bas
pkglibdir = $(libdir)/bas
pkglibexecdir = $(libexecdir)/bas
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = bas.fcgi$(EXEEXT)
subdir = cgi
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_bas_fcgi_OBJECTS = bas_fcgi-main.$(OBJEXT) \
	bas_fcgi-inputsDeal.$(OBJEXT) \
	bas_fcgi-getInputStruct.$(OBJEXT) \
	bas_fcgi-addQueryToEgg.$(OBJEXT) \
	bas_fcgi-getTimeStrings.$(OBJEXT) \
	bas_fcgi-getCollector.$(OBJEXT) \
	bas_fcgi-putInGstring.$(OBJEXT) \
	bas_fcgi-stringsReplace.$(OBJEXT) \
	bas_fcgi-hightlightAndSummary.$(OBJEXT) \
	bas_fcgi-findPositionStruct.$(OBJEXT) \
	bas_fcgi-pKeywords.$(OBJEXT) bas_fcgi-config.$(OBJEXT) \
	bas_fcgi-findStringsWithoutCase.$(OBJEXT) \
	bas_fcgi-mylog.$(OBJEXT)
bas_fcgi_OBJECTS = $(am_bas_fcgi_OBJECTS)
bas_fcgi_DEPENDENCIES =
bas_fcgi_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(bas_fcgi_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(bas_fcgi_SOURCES)
DIST_SOURCES = $(bas_fcgi_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/missing --run tar
AM_CFLAGS = -I/usr/local/include -I/usr/local/include/w3c-libwww -DHAVE_CONFIG_H -I/usr/local/include/egg2 -I/usr/local/include/scholar -I/usr/local/include/bigfile -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include  
AM_LDFLAGS = -L/usr/local/lib -lwwwxml -lxmltok -lxmlparse -lwwwinit -lwwwapp -lwwwhtml -lwwwtelnet -lwwwnews -lwwwhttp -lwwwmime -lwwwgopher -lwwwftp -lwwwfile -lwwwdir -lwwwcache -lwwwstream -lwwwmux -lwwwtrans -lwwwcore -lwwwutils -lmd5 -ldl -L/usr/local/lib -lglib-2.0  
AR = ar
AUTOCONF = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/missing --run autoconf
AUTOHEADER = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/missing --run autoheader
AUTOMAKE = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -Wall -O0
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g3 -Wall -O0 -pg
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"bas\" -DPACKAGE_TARNAME=\"bas\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"bas\ 1.0\" -DPACKAGE_BUGREPORT=\"qingdong.meng@ape-tech.com\" -DPACKAGE=\"bas\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBEGG2=1 -DSTDC_HEADERS=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_ALARM=1 -DHAVE_LOCALTIME_R=1 -DHAVE_MEMSET=1 -DHAVE_REGCOMP=1 -DHAVE_TZSET=1 -D_GNU_SOURCE=1
DEPDIR = .deps
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = -g3 -O0 -Wall -pg
LIBOBJS = 
LIBS = -legg2 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = bas
PACKAGE_BUGREPORT = qingdong.meng@ape-tech.com
PACKAGE_NAME = bas
PACKAGE_STRING = bas 1.0
PACKAGE_TARNAME = bas
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.0
abs_builddir = /home/ape/.ape/Dev/cvs/ImRoBot5/bas/cgi
abs_srcdir = /home/ape/.ape/Dev/cvs/ImRoBot5/bas/cgi
abs_top_builddir = /home/ape/.ape/Dev/cvs/ImRoBot5/bas
abs_top_srcdir = /home/ape/.ape/Dev/cvs/ImRoBot5/bas
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
cppunit_CFLAGS = -I/usr/local/include  
cppunit_LIBS = -L/usr/local/lib -lcppunit  
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
glib_CFLAGS = -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include  
glib_LIBS = -L/usr/local/lib -lglib-2.0  
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/ape/.ape/Dev/cvs/ImRoBot5/bas/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
libxml_CFLAGS = -I/usr/include/libxml2  
libxml_LIBS = -lxml2  
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
AUTOMAKE_OPTIONS = foreign
bas_fcgi_SOURCES = main.c\
      inputsDeal.c\
      getInputStruct.c\
      addQueryToEgg.c\
      getTimeStrings.c\
      getCollector.c\
      putInGstring.c\
      stringsReplace.c\
      hightlightAndSummary.c\
      findPositionStruct.c\
      pKeywords.c\
      config.c\
      findStringsWithoutCase.c\
      mylog.c 

bas_fcgi_CFLAGS = $(glib_CFLAGS) -g -Wall -O0 -pg -I/usr/local/include/spdindex/ -L/usr/log4c/lib/ -I/usr/log4c/include /usr/local/log4c/lib/liblog4c.so 
bas_fcgi_LDADD = -lfcgi -lscholar -legg2 -lspdindex
all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign cgi/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign cgi/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
bas.fcgi$(EXEEXT): $(bas_fcgi_OBJECTS) $(bas_fcgi_DEPENDENCIES) 
	@rm -f bas.fcgi$(EXEEXT)
	$(bas_fcgi_LINK) $(bas_fcgi_OBJECTS) $(bas_fcgi_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/bas_fcgi-addQueryToEgg.Po
include ./$(DEPDIR)/bas_fcgi-config.Po
include ./$(DEPDIR)/bas_fcgi-findPositionStruct.Po
include ./$(DEPDIR)/bas_fcgi-findStringsWithoutCase.Po
include ./$(DEPDIR)/bas_fcgi-getCollector.Po
include ./$(DEPDIR)/bas_fcgi-getInputStruct.Po
include ./$(DEPDIR)/bas_fcgi-getTimeStrings.Po
include ./$(DEPDIR)/bas_fcgi-hightlightAndSummary.Po
include ./$(DEPDIR)/bas_fcgi-inputsDeal.Po
include ./$(DEPDIR)/bas_fcgi-main.Po
include ./$(DEPDIR)/bas_fcgi-mylog.Po
include ./$(DEPDIR)/bas_fcgi-pKeywords.Po
include ./$(DEPDIR)/bas_fcgi-putInGstring.Po
include ./$(DEPDIR)/bas_fcgi-stringsReplace.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

bas_fcgi-main.o: main.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-main.o -MD -MP -MF $(DEPDIR)/bas_fcgi-main.Tpo -c -o bas_fcgi-main.o `test -f 'main.c' || echo '$(srcdir)/'`main.c
	$(am__mv) $(DEPDIR)/bas_fcgi-main.Tpo $(DEPDIR)/bas_fcgi-main.Po
#	source='main.c' object='bas_fcgi-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-main.o `test -f 'main.c' || echo '$(srcdir)/'`main.c

bas_fcgi-main.obj: main.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-main.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-main.Tpo -c -o bas_fcgi-main.obj `if test -f 'main.c'; then $(CYGPATH_W) 'main.c'; else $(CYGPATH_W) '$(srcdir)/main.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-main.Tpo $(DEPDIR)/bas_fcgi-main.Po
#	source='main.c' object='bas_fcgi-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-main.obj `if test -f 'main.c'; then $(CYGPATH_W) 'main.c'; else $(CYGPATH_W) '$(srcdir)/main.c'; fi`

bas_fcgi-inputsDeal.o: inputsDeal.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-inputsDeal.o -MD -MP -MF $(DEPDIR)/bas_fcgi-inputsDeal.Tpo -c -o bas_fcgi-inputsDeal.o `test -f 'inputsDeal.c' || echo '$(srcdir)/'`inputsDeal.c
	$(am__mv) $(DEPDIR)/bas_fcgi-inputsDeal.Tpo $(DEPDIR)/bas_fcgi-inputsDeal.Po
#	source='inputsDeal.c' object='bas_fcgi-inputsDeal.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-inputsDeal.o `test -f 'inputsDeal.c' || echo '$(srcdir)/'`inputsDeal.c

bas_fcgi-inputsDeal.obj: inputsDeal.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-inputsDeal.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-inputsDeal.Tpo -c -o bas_fcgi-inputsDeal.obj `if test -f 'inputsDeal.c'; then $(CYGPATH_W) 'inputsDeal.c'; else $(CYGPATH_W) '$(srcdir)/inputsDeal.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-inputsDeal.Tpo $(DEPDIR)/bas_fcgi-inputsDeal.Po
#	source='inputsDeal.c' object='bas_fcgi-inputsDeal.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-inputsDeal.obj `if test -f 'inputsDeal.c'; then $(CYGPATH_W) 'inputsDeal.c'; else $(CYGPATH_W) '$(srcdir)/inputsDeal.c'; fi`

bas_fcgi-getInputStruct.o: getInputStruct.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-getInputStruct.o -MD -MP -MF $(DEPDIR)/bas_fcgi-getInputStruct.Tpo -c -o bas_fcgi-getInputStruct.o `test -f 'getInputStruct.c' || echo '$(srcdir)/'`getInputStruct.c
	$(am__mv) $(DEPDIR)/bas_fcgi-getInputStruct.Tpo $(DEPDIR)/bas_fcgi-getInputStruct.Po
#	source='getInputStruct.c' object='bas_fcgi-getInputStruct.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-getInputStruct.o `test -f 'getInputStruct.c' || echo '$(srcdir)/'`getInputStruct.c

bas_fcgi-getInputStruct.obj: getInputStruct.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-getInputStruct.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-getInputStruct.Tpo -c -o bas_fcgi-getInputStruct.obj `if test -f 'getInputStruct.c'; then $(CYGPATH_W) 'getInputStruct.c'; else $(CYGPATH_W) '$(srcdir)/getInputStruct.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-getInputStruct.Tpo $(DEPDIR)/bas_fcgi-getInputStruct.Po
#	source='getInputStruct.c' object='bas_fcgi-getInputStruct.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-getInputStruct.obj `if test -f 'getInputStruct.c'; then $(CYGPATH_W) 'getInputStruct.c'; else $(CYGPATH_W) '$(srcdir)/getInputStruct.c'; fi`

bas_fcgi-addQueryToEgg.o: addQueryToEgg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-addQueryToEgg.o -MD -MP -MF $(DEPDIR)/bas_fcgi-addQueryToEgg.Tpo -c -o bas_fcgi-addQueryToEgg.o `test -f 'addQueryToEgg.c' || echo '$(srcdir)/'`addQueryToEgg.c
	$(am__mv) $(DEPDIR)/bas_fcgi-addQueryToEgg.Tpo $(DEPDIR)/bas_fcgi-addQueryToEgg.Po
#	source='addQueryToEgg.c' object='bas_fcgi-addQueryToEgg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-addQueryToEgg.o `test -f 'addQueryToEgg.c' || echo '$(srcdir)/'`addQueryToEgg.c

bas_fcgi-addQueryToEgg.obj: addQueryToEgg.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-addQueryToEgg.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-addQueryToEgg.Tpo -c -o bas_fcgi-addQueryToEgg.obj `if test -f 'addQueryToEgg.c'; then $(CYGPATH_W) 'addQueryToEgg.c'; else $(CYGPATH_W) '$(srcdir)/addQueryToEgg.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-addQueryToEgg.Tpo $(DEPDIR)/bas_fcgi-addQueryToEgg.Po
#	source='addQueryToEgg.c' object='bas_fcgi-addQueryToEgg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-addQueryToEgg.obj `if test -f 'addQueryToEgg.c'; then $(CYGPATH_W) 'addQueryToEgg.c'; else $(CYGPATH_W) '$(srcdir)/addQueryToEgg.c'; fi`

bas_fcgi-getTimeStrings.o: getTimeStrings.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-getTimeStrings.o -MD -MP -MF $(DEPDIR)/bas_fcgi-getTimeStrings.Tpo -c -o bas_fcgi-getTimeStrings.o `test -f 'getTimeStrings.c' || echo '$(srcdir)/'`getTimeStrings.c
	$(am__mv) $(DEPDIR)/bas_fcgi-getTimeStrings.Tpo $(DEPDIR)/bas_fcgi-getTimeStrings.Po
#	source='getTimeStrings.c' object='bas_fcgi-getTimeStrings.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-getTimeStrings.o `test -f 'getTimeStrings.c' || echo '$(srcdir)/'`getTimeStrings.c

bas_fcgi-getTimeStrings.obj: getTimeStrings.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-getTimeStrings.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-getTimeStrings.Tpo -c -o bas_fcgi-getTimeStrings.obj `if test -f 'getTimeStrings.c'; then $(CYGPATH_W) 'getTimeStrings.c'; else $(CYGPATH_W) '$(srcdir)/getTimeStrings.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-getTimeStrings.Tpo $(DEPDIR)/bas_fcgi-getTimeStrings.Po
#	source='getTimeStrings.c' object='bas_fcgi-getTimeStrings.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-getTimeStrings.obj `if test -f 'getTimeStrings.c'; then $(CYGPATH_W) 'getTimeStrings.c'; else $(CYGPATH_W) '$(srcdir)/getTimeStrings.c'; fi`

bas_fcgi-getCollector.o: getCollector.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-getCollector.o -MD -MP -MF $(DEPDIR)/bas_fcgi-getCollector.Tpo -c -o bas_fcgi-getCollector.o `test -f 'getCollector.c' || echo '$(srcdir)/'`getCollector.c
	$(am__mv) $(DEPDIR)/bas_fcgi-getCollector.Tpo $(DEPDIR)/bas_fcgi-getCollector.Po
#	source='getCollector.c' object='bas_fcgi-getCollector.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-getCollector.o `test -f 'getCollector.c' || echo '$(srcdir)/'`getCollector.c

bas_fcgi-getCollector.obj: getCollector.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-getCollector.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-getCollector.Tpo -c -o bas_fcgi-getCollector.obj `if test -f 'getCollector.c'; then $(CYGPATH_W) 'getCollector.c'; else $(CYGPATH_W) '$(srcdir)/getCollector.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-getCollector.Tpo $(DEPDIR)/bas_fcgi-getCollector.Po
#	source='getCollector.c' object='bas_fcgi-getCollector.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-getCollector.obj `if test -f 'getCollector.c'; then $(CYGPATH_W) 'getCollector.c'; else $(CYGPATH_W) '$(srcdir)/getCollector.c'; fi`

bas_fcgi-putInGstring.o: putInGstring.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-putInGstring.o -MD -MP -MF $(DEPDIR)/bas_fcgi-putInGstring.Tpo -c -o bas_fcgi-putInGstring.o `test -f 'putInGstring.c' || echo '$(srcdir)/'`putInGstring.c
	$(am__mv) $(DEPDIR)/bas_fcgi-putInGstring.Tpo $(DEPDIR)/bas_fcgi-putInGstring.Po
#	source='putInGstring.c' object='bas_fcgi-putInGstring.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-putInGstring.o `test -f 'putInGstring.c' || echo '$(srcdir)/'`putInGstring.c

bas_fcgi-putInGstring.obj: putInGstring.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-putInGstring.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-putInGstring.Tpo -c -o bas_fcgi-putInGstring.obj `if test -f 'putInGstring.c'; then $(CYGPATH_W) 'putInGstring.c'; else $(CYGPATH_W) '$(srcdir)/putInGstring.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-putInGstring.Tpo $(DEPDIR)/bas_fcgi-putInGstring.Po
#	source='putInGstring.c' object='bas_fcgi-putInGstring.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-putInGstring.obj `if test -f 'putInGstring.c'; then $(CYGPATH_W) 'putInGstring.c'; else $(CYGPATH_W) '$(srcdir)/putInGstring.c'; fi`

bas_fcgi-stringsReplace.o: stringsReplace.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-stringsReplace.o -MD -MP -MF $(DEPDIR)/bas_fcgi-stringsReplace.Tpo -c -o bas_fcgi-stringsReplace.o `test -f 'stringsReplace.c' || echo '$(srcdir)/'`stringsReplace.c
	$(am__mv) $(DEPDIR)/bas_fcgi-stringsReplace.Tpo $(DEPDIR)/bas_fcgi-stringsReplace.Po
#	source='stringsReplace.c' object='bas_fcgi-stringsReplace.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-stringsReplace.o `test -f 'stringsReplace.c' || echo '$(srcdir)/'`stringsReplace.c

bas_fcgi-stringsReplace.obj: stringsReplace.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-stringsReplace.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-stringsReplace.Tpo -c -o bas_fcgi-stringsReplace.obj `if test -f 'stringsReplace.c'; then $(CYGPATH_W) 'stringsReplace.c'; else $(CYGPATH_W) '$(srcdir)/stringsReplace.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-stringsReplace.Tpo $(DEPDIR)/bas_fcgi-stringsReplace.Po
#	source='stringsReplace.c' object='bas_fcgi-stringsReplace.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-stringsReplace.obj `if test -f 'stringsReplace.c'; then $(CYGPATH_W) 'stringsReplace.c'; else $(CYGPATH_W) '$(srcdir)/stringsReplace.c'; fi`

bas_fcgi-hightlightAndSummary.o: hightlightAndSummary.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-hightlightAndSummary.o -MD -MP -MF $(DEPDIR)/bas_fcgi-hightlightAndSummary.Tpo -c -o bas_fcgi-hightlightAndSummary.o `test -f 'hightlightAndSummary.c' || echo '$(srcdir)/'`hightlightAndSummary.c
	$(am__mv) $(DEPDIR)/bas_fcgi-hightlightAndSummary.Tpo $(DEPDIR)/bas_fcgi-hightlightAndSummary.Po
#	source='hightlightAndSummary.c' object='bas_fcgi-hightlightAndSummary.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-hightlightAndSummary.o `test -f 'hightlightAndSummary.c' || echo '$(srcdir)/'`hightlightAndSummary.c

bas_fcgi-hightlightAndSummary.obj: hightlightAndSummary.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-hightlightAndSummary.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-hightlightAndSummary.Tpo -c -o bas_fcgi-hightlightAndSummary.obj `if test -f 'hightlightAndSummary.c'; then $(CYGPATH_W) 'hightlightAndSummary.c'; else $(CYGPATH_W) '$(srcdir)/hightlightAndSummary.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-hightlightAndSummary.Tpo $(DEPDIR)/bas_fcgi-hightlightAndSummary.Po
#	source='hightlightAndSummary.c' object='bas_fcgi-hightlightAndSummary.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-hightlightAndSummary.obj `if test -f 'hightlightAndSummary.c'; then $(CYGPATH_W) 'hightlightAndSummary.c'; else $(CYGPATH_W) '$(srcdir)/hightlightAndSummary.c'; fi`

bas_fcgi-findPositionStruct.o: findPositionStruct.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-findPositionStruct.o -MD -MP -MF $(DEPDIR)/bas_fcgi-findPositionStruct.Tpo -c -o bas_fcgi-findPositionStruct.o `test -f 'findPositionStruct.c' || echo '$(srcdir)/'`findPositionStruct.c
	$(am__mv) $(DEPDIR)/bas_fcgi-findPositionStruct.Tpo $(DEPDIR)/bas_fcgi-findPositionStruct.Po
#	source='findPositionStruct.c' object='bas_fcgi-findPositionStruct.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-findPositionStruct.o `test -f 'findPositionStruct.c' || echo '$(srcdir)/'`findPositionStruct.c

bas_fcgi-findPositionStruct.obj: findPositionStruct.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-findPositionStruct.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-findPositionStruct.Tpo -c -o bas_fcgi-findPositionStruct.obj `if test -f 'findPositionStruct.c'; then $(CYGPATH_W) 'findPositionStruct.c'; else $(CYGPATH_W) '$(srcdir)/findPositionStruct.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-findPositionStruct.Tpo $(DEPDIR)/bas_fcgi-findPositionStruct.Po
#	source='findPositionStruct.c' object='bas_fcgi-findPositionStruct.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-findPositionStruct.obj `if test -f 'findPositionStruct.c'; then $(CYGPATH_W) 'findPositionStruct.c'; else $(CYGPATH_W) '$(srcdir)/findPositionStruct.c'; fi`

bas_fcgi-pKeywords.o: pKeywords.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-pKeywords.o -MD -MP -MF $(DEPDIR)/bas_fcgi-pKeywords.Tpo -c -o bas_fcgi-pKeywords.o `test -f 'pKeywords.c' || echo '$(srcdir)/'`pKeywords.c
	$(am__mv) $(DEPDIR)/bas_fcgi-pKeywords.Tpo $(DEPDIR)/bas_fcgi-pKeywords.Po
#	source='pKeywords.c' object='bas_fcgi-pKeywords.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-pKeywords.o `test -f 'pKeywords.c' || echo '$(srcdir)/'`pKeywords.c

bas_fcgi-pKeywords.obj: pKeywords.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-pKeywords.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-pKeywords.Tpo -c -o bas_fcgi-pKeywords.obj `if test -f 'pKeywords.c'; then $(CYGPATH_W) 'pKeywords.c'; else $(CYGPATH_W) '$(srcdir)/pKeywords.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-pKeywords.Tpo $(DEPDIR)/bas_fcgi-pKeywords.Po
#	source='pKeywords.c' object='bas_fcgi-pKeywords.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-pKeywords.obj `if test -f 'pKeywords.c'; then $(CYGPATH_W) 'pKeywords.c'; else $(CYGPATH_W) '$(srcdir)/pKeywords.c'; fi`

bas_fcgi-config.o: config.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-config.o -MD -MP -MF $(DEPDIR)/bas_fcgi-config.Tpo -c -o bas_fcgi-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c
	$(am__mv) $(DEPDIR)/bas_fcgi-config.Tpo $(DEPDIR)/bas_fcgi-config.Po
#	source='config.c' object='bas_fcgi-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c

bas_fcgi-config.obj: config.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-config.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-config.Tpo -c -o bas_fcgi-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-config.Tpo $(DEPDIR)/bas_fcgi-config.Po
#	source='config.c' object='bas_fcgi-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`

bas_fcgi-findStringsWithoutCase.o: findStringsWithoutCase.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-findStringsWithoutCase.o -MD -MP -MF $(DEPDIR)/bas_fcgi-findStringsWithoutCase.Tpo -c -o bas_fcgi-findStringsWithoutCase.o `test -f 'findStringsWithoutCase.c' || echo '$(srcdir)/'`findStringsWithoutCase.c
	$(am__mv) $(DEPDIR)/bas_fcgi-findStringsWithoutCase.Tpo $(DEPDIR)/bas_fcgi-findStringsWithoutCase.Po
#	source='findStringsWithoutCase.c' object='bas_fcgi-findStringsWithoutCase.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-findStringsWithoutCase.o `test -f 'findStringsWithoutCase.c' || echo '$(srcdir)/'`findStringsWithoutCase.c

bas_fcgi-findStringsWithoutCase.obj: findStringsWithoutCase.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-findStringsWithoutCase.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-findStringsWithoutCase.Tpo -c -o bas_fcgi-findStringsWithoutCase.obj `if test -f 'findStringsWithoutCase.c'; then $(CYGPATH_W) 'findStringsWithoutCase.c'; else $(CYGPATH_W) '$(srcdir)/findStringsWithoutCase.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-findStringsWithoutCase.Tpo $(DEPDIR)/bas_fcgi-findStringsWithoutCase.Po
#	source='findStringsWithoutCase.c' object='bas_fcgi-findStringsWithoutCase.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-findStringsWithoutCase.obj `if test -f 'findStringsWithoutCase.c'; then $(CYGPATH_W) 'findStringsWithoutCase.c'; else $(CYGPATH_W) '$(srcdir)/findStringsWithoutCase.c'; fi`

bas_fcgi-mylog.o: mylog.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-mylog.o -MD -MP -MF $(DEPDIR)/bas_fcgi-mylog.Tpo -c -o bas_fcgi-mylog.o `test -f 'mylog.c' || echo '$(srcdir)/'`mylog.c
	$(am__mv) $(DEPDIR)/bas_fcgi-mylog.Tpo $(DEPDIR)/bas_fcgi-mylog.Po
#	source='mylog.c' object='bas_fcgi-mylog.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-mylog.o `test -f 'mylog.c' || echo '$(srcdir)/'`mylog.c

bas_fcgi-mylog.obj: mylog.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -MT bas_fcgi-mylog.obj -MD -MP -MF $(DEPDIR)/bas_fcgi-mylog.Tpo -c -o bas_fcgi-mylog.obj `if test -f 'mylog.c'; then $(CYGPATH_W) 'mylog.c'; else $(CYGPATH_W) '$(srcdir)/mylog.c'; fi`
	$(am__mv) $(DEPDIR)/bas_fcgi-mylog.Tpo $(DEPDIR)/bas_fcgi-mylog.Po
#	source='mylog.c' object='bas_fcgi-mylog.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bas_fcgi_CFLAGS) $(CFLAGS) -c -o bas_fcgi-mylog.obj `if test -f 'mylog.c'; then $(CYGPATH_W) 'mylog.c'; else $(CYGPATH_W) '$(srcdir)/mylog.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool ctags distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags uninstall uninstall-am \
	uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
